In [1]:
#The aim of this
#Task is to find out which are the most relevant features that students consider
#to choose their preferred American university. Some of the essential questions
#for developing this project are related to the number of applications,
#admissions, and enrollments, cost of tuition and fees, cost of living on
#campus, types of degrees offered, and features of the states where universities
#are located (population and GDP).


#The dataset
#used for this analysis was taken from 


#https://www.kaggle.com/sumithbhongale/american-university-data-ipeds-dataset.


#Try to answer the following hypotheses and questions:

In [1]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
american_uni = pd.read_csv("archive\IPEDS_data.csv",delimiter=";")
american_uni.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Columns: 145 entries, ID number to Endowment assets (year end) per FTE enrollment (FASB)
dtypes: float64(116), int64(2), object(27)
memory usage: 1.7+ MB

In [21]:
american_uni.describe()

,ID number,year,Longitude location of institution,Latitude location of institution,Applicants total,Admissions total,Enrolled total,Percent of freshmen submitting SAT scores,Percent of freshmen submitting ACT scores,SAT Critical Reading 25th percentile score,SAT Critical Reading 75th percentile score,SAT Math 25th percentile score,SAT Math 75th percentile score,SAT Writing 25th percentile score,SAT Writing 75th percentile score,ACT Composite 25th percentile score,ACT Composite 75th percentile score,"Estimated enrollment, total","Estimated enrollment, full time","Estimated enrollment, part time","Estimated undergraduate enrollment, total","Estimated undergraduate enrollment, full time","Estimated undergraduate enrollment, part time","Estimated freshman undergraduate enrollment, total","Estimated freshman enrollment, full time","Estimated freshman enrollment, part time","Estimated graduate enrollment, total","Estimated graduate enrollment, full time","Estimated graduate enrollment, part time",Associate's degrees awarded,Bachelor's degrees awarded,Master's degrees awarded,Doctor's degrese - research/scholarship awarded,Doctor's degrees - professional practice awarded,Doctor's degrees - other awarded,Certificates of less than 1-year awarded,Certificates of 1 but less than 2-years awarded,Certificates of 2 but less than 4-years awarded,Postbaccalaureate certificates awarded,Post-master's certificates awarded,Number of students receiving an Associate's degree,Number of students receiving a Bachelor's degree,Number of students receiving a Master's degree,Number of students receiving a Doctor's degree,Number of students receiving a certificate of less than 1-year,Number of students receiving a certificate of 1 but less than 4-years,Number of students receiving a Postbaccalaureate or Post-master's certificate,Percent admitted - total,Admissions yield - total,"Tuition and fees, 2010-11","Tuition and fees, 2011-12","Tuition and fees, 2012-13","Tuition and fees, 2013-14",Total price for in-state students living on campus 2013-14,Total price for out-of-state students living on campus 2013-14,Total enrollment,Full-time enrollment,Part-time enrollment,Undergraduate enrollment,Graduate enrollment,Full-time undergraduate enrollment,Part-time undergraduate enrollment,Percent of total enrollment that are American Indian or Alaska Native,Percent of total enrollment that are Asian,Percent of total enrollment that are Black or African American,Percent of total enrollment that are Hispanic/Latino,Percent of total enrollment that are Native Hawaiian or Other Pacific Islander,Percent of total enrollment that are White,Percent of total enrollment that are two or more races,Percent of total enrollment that are Race/ethnicity unknown,Percent of total enrollment that are Nonresident Alien,Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of total enrollment that are women,Percent of undergraduate enrollment that are American Indian or Alaska Native,Percent of undergraduate enrollment that are Asian,Percent of undergraduate enrollment that are Black or African American,Percent of undergraduate enrollment that are Hispanic/Latino,Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander,Percent of undergraduate enrollment that are White,Percent of undergraduate enrollment that are two or more races,Percent of undergraduate enrollment that are Race/ethnicity unknown,Percent of undergraduate enrollment that are Nonresident Alien,Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of undergraduate enrollment that are women,Percent of graduate enrollment that are American Indian or Alaska Native,Percent of graduate enrollment that are Asian,Percent of graduate enrollment that are Black or African American,Percent of graduate enrollment that are Hispanic/Latino,Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander,Percent of graduate enrollment that are White,Percent of graduate enrollment that are two or more races,Percent of graduate enrollment that are Race/ethnicity unknown,Percent of graduate enrollment that are Nonresident Alien,Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of graduate enrollment that are women,Number of first-time undergraduates - in-state,Percent of first-time undergraduates - in-state,Number of first-time undergraduates - out-of-state,Percent of first-time undergraduates - out-of-state,Number of first-time undergraduates - foreign countries,Percent of first-time undergraduates - foreign countries,Number of first-time undergraduates - residence unknown,Percent of first-time undergraduates - residence unknown,"Graduation rate - Bachelor degree within 4 years, total","Graduation rate - Bachelor degree within 5 years, total","Graduation rate - Bachelor degree within 6 years, total",Percent of freshmen receiving any financial aid,"Percent of freshmen receiving federal, state, local or institutional grant aid",Percent of freshmen receiving federal grant aid,Percent of freshmen receiving Pell grants,Percent of freshmen receiving other federal grant aid,Percent of freshmen receiving state/local grant aid,Percent of freshmen receiving institutional grant aid,Percent of freshmen receiving student loan aid,Percent of freshmen receiving federal student loans,Percent of freshmen receiving other loan aid,Endowment assets (year end) per FTE enrollment (GASB),Endowment assets (year end) per FTE enrollment (FASB)
count,1534.000000,1534.0,1534.000000,1534.000000,1377.000000,1377.000000,1377.000000,1257.000000,1259.000000,1169.000000,1169.000000,1182.000000,1182.000000,714.000000,714.000000,1199.000000,1199.000000,1532.000000,1531.000000,1523.000000,1526.000000,1525.000000,1514.000000,1515.000000,1515.000000,1451.000000,1432.000000,1422.000000,1420.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1376.000000,1376.000000,1490.000000,1490.000000,1492.000000,1497.000000,1400.000000,1400.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1532.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1522.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,1269.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,1476.000000,1476.000000,1476.000000,1492.000000,1492.000000,1492.00000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,516.000000,9.600000e+02
mean,189091.037810,2013.0,-88.342338,38.729993,6391.193174,3554.880174,1043.046478,53.927605,53.085782,470.340462,578.297690,480.514382,588.311337,470.931373,576.550420,20.582152,25.572143,7033.115535,5367.621816,1678.860144,5524.874181,4524.734426,1011.055482,994.761716,964.522772,31.572708,1636.714385,926.588608,722.652113,52.819843,1070.459530,414.700392,38.181462,51.039817,0.402742,7.830940,4.907311,1.062663,18.530026,10.453655,52.435379,1055.548303,412.077023,89.370104,7.421671,5.766971,28.406658,64.569767,33.062500,18355.520805,19243.977181,20046.977882,20727.490314,34935.306429,38767.612857,7070.114230,5371.494125,1698.620104,5532.885117,1537.229112,4507.738903,1025.146214,0.614883,3.757833,13.768930,8.524804,0.161227,59.998042,2.398172,6.056136,4.500653,4.018930,57.911227,0.635348,3.908673,14.015769,9.243101,0.173456,59.970434,2.590013,5.637319,3.597240,4.187254,57.169514,0.572892,3.526399,11.251379,6.109535,0.119779,60.962963,1.389283,8.386131,7.550039,3.713948,63.109535,896.720088,69.170143,292.670692,27.216246,42.178924,2.990121,6.545554,0.589462,37.450542,49.788618,53.189024,90.672252,84.464477,41.47185,40.764075,15.418901,35.384718,70.335121,64.959786,64.180295,7.553619,9459.463178,6.503032e+04
std,58641.915456,0.0,14.838804,4.832832,8787.469171,4309.457606,1285.165519,34.385164,31.658662,68.368390,70.169391,72.464475,71.871189,79.670620,78.899075,3.477768,3.375932,9387.648898,7462.468258,2894.533965,7212.902926,6032.739533,2092.958526,1273.252943,1235.496629,128.451663,2837.446817,1916.618468,1239.369189,216.684048,1504.503006,719.869639,116.127156,140.823584,3.737685,49.416393,25.793771,15.615982,63.021471,45.436785,214.749408,1471.434130,713.932918,234.943952,46.242592,29.803951,78.380687,18.710062,14.994608,11147.155940,11549.561574,11982.294510,12455.805360,13283.049319,10716.524007,9416.538854,7474.494963,2922.064160,7242.649546,2765.197979,6042.192662,2121.495422,2.266212,4.975128,19.704118,10.691080,1.191406,22.277670,2.132317,7.335533,5.983594,5.396279,11.784477,2.306641,5.608432,20.046849,11.437796,1.205458,22.957378,2.280202,7.255540,4.463904,6.003923,11.886220,1.835186,4.392635,16.127176,9.182507,0.794199,21.351299,2.014869,10.715080,11.122634,4.573201,14.147092,1114.720451,24.856393,451.362286,23.182942,102.747668,4.311614,26.157508,2.321060,21.949856,20.256726,19.102511,11.963692,17.304491,18.88068,18.560557,14.091423,21.897744,29.463324,19.143070,19.337354,7.706674,19398.443224,1.773784e+05
min,100654.000000,2013.0,-158.062444,19.701854,0.000000,0.000000,0.000000,0.000000,0.000000,310.000000,360.000000,280.000000,410.000000,310.000000,360.000000,13.000000,14.000000,68.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,910.000000,910.000000,2496.000000,1032.000000,9768.000000,9768.000000,66.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,10.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.000000,4.200000e+01
25%,153148.500000,2013.0,-94.576341,35.348340,1488.000000,950.000000,287.000000,16.000000,26.000000,430.000000,530.000000,430.000000,540.000000,416.250000,520.000000,18.000000,23.000000,1497.250000,1199.500000,168.000000,1333.000000,1114.000000,88.000000,263.000000,251.500000,0.000000,91.750000,29.000000,31.000000,0.000000,246.750000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,242.000000,13.000000,0.000000,0.000000,0.000000,0.000000,54.000000,22.000000,7420.500000,7907.250000,8182.500000,8542.000000,22487.000000,31128.000000,1512.750000,1199.000000,167.000000,1328.000000,46.750000,1089.500000,87.000000,0.000000,1.000000,4.000000,3.000000,0.000000,50.000000,1.000000,1.000000,1.000000,1.000000,52.000000,0.000000,1.000000,4.000000,3.000000,0.000000,50.000000,1.000000,1.000000,1.000000,1.000000,52.000000,0.000000,1.000000,3.000000,2.000000,0.000000,48.000000,0.000000,2.000000,1.000000,1.000000,55.000000,192.500000,54.000000,50.000000,8.000000,2.000000,0.000000,0.000000,0.000000,20.000000,36.000000,40.000000,87.000000,73.000000,28.00000,27.000000,6.000000,18.000000,48.000000,54.000000,53.000000,2.000000,2080.000000,8.391000e+03
50%,186508.000000,2013.0,-84.514218,39.946096,3350.000000,2056.000000,538.000000,65.000000,49.000000,460.000000,570.000000,470.000000,580.000000,450.000000,566.500000,20.000000,25.000000,3126.000000,2335.000000,665.000000,2487.500000,2086.000000,321.000000,508.000000,495.000000,3.000000,568.500000,211.000000,283.000000,0.000000,482.000000,148.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,478.000000,148.500000,0.000000,0.000000,0.000000,0.000000,67.000000,30.000000,18000.000000,18765.000000,19470.000000,20060.000000,34115.000000,37193.500000,3127.000000,2328.000000,671.000000,2487.500000,471.000000,2066.000000,320.500000,0.000000,2.000000,7.000000,5.000000,0.000000,66.000000,2.000000,4.000000,3.000000,2.000000,58.000000,0.000000,2.000000,7.000000,6.000000,0.000000,66.000000,2.000000,3.000000,2.000000,2.000000,57.000000,0.000000,2.000000,6.000000,3.000000,0.000000,65.000000,1.000000,5.000000,3.000000,2.000000,64.000000,431.000000,76.000000,117.000000,21.000000,11.000000,1.000000,0.000000,0.000000,34.000000,49.000000,52.500000,95.000000,92.000000,40.00000,39.000000,12.000000,34.000000,78.000000,68.000000,67.000000,6.000000,4283.000000,1.870400e+04
75%,215730.000000,2013.0,-77.207136,41.984929,7016.000000,4203.000000,1246.000000,86.000000,87.000000,500.000000,620.000000,510.000000,630.000000,510.000000,620.000000,22.000000,27.000000,8376.000000,6043.000000,2029.500000,6291.500000,5227.000000,1090.000000,1155.500000,1134.500000,18.000000,1827.250000,811.000000,924.250000,16.000000,1212.000000,466.000000,8.250000,4.250000,0.000000,0.000000,0.000000,0.000000,4.000000,2.000000,16.000000,1206.750000,462.500000,38.000000,0.000000,0.000000,19.000000,78.000000,40.000000,26668.750000,27901.500000,29040.250000,29992.000000,44835.750000,45907.500000,8376.250000,6080.750000,2062.500000,6394.000000,1737.000000,5207.500000,1082.250000,1.000000,4.000000,14.000000,10.000000,0.000000,76.000000,3.000000,8.000000,6.000000,5.000000,63.000000,1.000000,4.000000,14.000000,10.000000,0.000000,77.000000,3.000000,7.000000,5.000000,5.000000,62.000000,1.000000,5.000000,12.000000,7.000000,0.000000,77.000000,2.000000,11.000000,10.000000,5.000000,72.000000,1159.500000,90.000000,330.500000,41.000000,38.500000,4.000000,3.000000,0.000000,52.250000,63.000000,66.000000,99.000000,99.000000,51.25000,51.000000,20.250000,50.000000,98.000000,79.000000,78.000000,11.000000,8715.500000,4.505250e+04
max,456490.000000,2013.0,-67.456534,64.857053,72676.000000,35815.000000,10241.000000,100.000000,100.000000,720.000000,800.000000,770.000000,800.000000,720.000000,800.000000,33.000000,35.000000,79576.000000,50012.000000,41704.000000,51269.000000,40020.000000,37668.000000,10241.000000,9030.000000,2554.000000,30599.000000,18166.000000,19620.000000,4077.000000,12320.000000,6965.000000,937.000000,1222.000000,87.000000,949.000000,481.000000,560.000000,781.000000,812.000000,3966.000000,12080.000000,6958.000000,1964.000000,862.000000,560.000000,899.000000,100.000000,100.000000,43990.000000,45290.000000,47246.000000,49138.000000,64988.000000,64988.000000,77338.000000,50012.000000,40985.000000,51333.000000,29874.000000,40020.000000,37440.000000,56.000000,40.000000,100.000000,98.000000,33.000000,100.000000,28.000000,73.000000,82.000000,65.000000,100.000000,56.000000,44.000000,100.000000,98.000000,33.000000,100.000000,29.000000,66.000000,56.000000,65.000000,100.000000,33.000000,50.000000,100.000000,98.000000,16.000000,100.000000,31.000000,88.000000,100.000000,50.000000,100.000000,9768.000000,100.000000,3704.000000,100.000000,1341.000000,40.000000,514.000000,47.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,83.000000,213079.000000,2.505435e+06

1.     
Do
universities with a high number of applications are the preferred ones by students?
in other words, could the number of applications tell us that a university is
one of the most preferred by students?

In [25]:
american_uni["Applicants total"].corr(american_uni["Enrolled total"])
# yes

0.7850451722765011

2.     
Do
students prefer universities that have a high rate of admission?, in other
words, do students prefer a university where it is easier for them to be
admitted?

In [27]:
american_uni["Applicants total"].corr(american_uni["Admissions total"])
# yes

0.854956183034936

3.     
Do
students prefer public or private universities?

In [48]:
american_uni["public or privat"]= american_uni["Sector of institution"].str.split(",",expand = True )[0]
american_uni["public or privat"].value_counts()
# privat ones

Private not-for-profit    971
Public                    563
Name: public or privat, dtype: int64

4.     
Do
students prefer universities with low tuition and fees?

In [57]:
american_uni[["Tuition and fees, 2010-11","Tuition and fees, 2011-12","Tuition and fees, 2012-13","Tuition and fees, 2013-14"]].mean(axis=1).corr(american_uni["Enrolled total"])
# no week relation

-0.3225223085587803

5.     
Do
students prefer a university for its low on-campus cost of living?

In [58]:
american_uni[["Total price for in-state students living on campus 2013-14","Total price for out-of-state students living on campus 2013-14"]].mean(axis=1).corr(american_uni["Enrolled total"])
# no correlation

-0.16020543728763847

6.     
Do
students prefer universities from highly populated states?

In [75]:
print(american_uni["Degree of urbanization (Urban-centric locale)"].unique())
american_uni["Enrolled total"].groupby(american_uni["Degree of urbanization (Urban-centric locale)"]).sum().sort_values()
# they prefares cities

['City: Midsize' 'City: Small' 'Town: Fringe' 'Town: Distant'
 'Rural: Remote' 'Suburb: Large' 'Rural: Fringe' 'City: Large'
 'Suburb: Small' 'Town: Remote' 'Rural: Distant' 'Suburb: Midsize']

Degree of urbanization (Urban-centric locale)
Rural: Remote        2825.0
Rural: Distant       6296.0
Rural: Fringe       27286.0
Town: Fringe        38609.0
Suburb: Small       39649.0
Suburb: Midsize     47585.0
Town: Remote        83270.0
Town: Distant      108015.0
Suburb: Large      217852.0
City: Midsize      228197.0
City: Small        290918.0
City: Large        345773.0
Name: Enrolled total, dtype: float64

7.     
Do
students prefer a university because it belongs to a state with a high GDP per
capita?

In [ ]:
# i don't know what feature to use

8.     
Do
students prefer a university based on the possibility of a higher, additional
academic degree in the same university?

In [74]:
american_uni["Enrolled total"].groupby(american_uni["Highest degree offered"]).sum()
#yes

Highest degree offered
Bachelor's degree                                                    87123.0
Doctor's degree -  professional practice                             94416.0
Doctor's degree - other                                              34072.0
Doctor's degree - research/scholarship                              205698.0
Doctor's degree - research/scholarship and professional practice    724399.0
Master's degree                                                     290567.0
Name: Enrolled total, dtype: float64

In [72]:
american_uni["Enrolled total"].groupby(american_uni["Offers Master's degree"]).sum()

Offers Master's degree
Implied no      87419.0
Yes           1348856.0
Name: Enrolled total, dtype: float64

In [73]:
american_uni["Enrolled total"].groupby(american_uni["Offers Doctor's degree - research/scholarship"]).sum()

Offers Doctor's degree - research/scholarship
Implied no    506178.0
Yes           930097.0
Name: Enrolled total, dtype: float64